### ISSUE TITLE
Make thumbBox Resizable

### ISSUE THREAD

**Issue by tommyready** [hongkhanh/cropbox#1]
Hey,

This really isnt an issue but more like a question.  Is there a way to make the thumbBox resizable?  I was trying to use jQuery UI resizable function but that doesnt seem to work for me.  Any sugguests/Thoughts?

TR

**Comment by hongkhanh** [comment]
Hi,

Thanks for your question. There is a simple way that you can use CSS3 resize as the following link
http://jsfiddle.net/epinapala/KFr2z/
I will add this feature soon.

NHK
