### ISSUE TITLE
Change background to white

### ISSUE THREAD

**Issue by jethrubalarbar** [hongkhanh/cropbox#2]
Your code can crop a png file with transparent background but it turns it into black background, Is it possible to upload a png file with transparent background and turns into white bg. Thanks. Cheers.

**Comment by hongkhanh** [comment]
Hi, I have changed image type from image/jpeg to image/png. Therefore, the background now is transparent. Cheers

**Comment by jethrubalarbar** [comment]
Thanks mate. :D Lovin' the result. Cheers

**Comment by jethrubalarbar** [comment]
Hello mate, I discovered a browser issue specially on safari, SOME PHOTOS lower than 100kb rendered black after cropping. Hope you can help me on this. Thanks and CHEERS!

**Comment by hongkhanh** [comment]
thanks for your feedback, I will take a look on this, cheers
